-- Money is stored as integer paise. Never floats.

DROP TABLE IF EXISTS bids;
DROP TABLE IF EXISTS auctions;

CREATE TABLE auctions (
  id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
  status               ENUM('OPEN', 'CLOSED') NOT NULL DEFAULT 'OPEN',
  start_price          BIGINT NOT NULL,          -- first bid must be at or below this
  decrement_step       BIGINT NOT NULL,          -- each new bid must beat the best by at least this
  best_bid             BIGINT NULL,
  best_bidder          BIGINT NULL,
  end_time             DATETIME(3) NOT NULL,
  extension_window_sec INT NOT NULL,             -- a bid inside this window extends the auction
  extension_count      INT NOT NULL DEFAULT 0,
  max_extensions       INT NOT NULL              -- cap, so an auction can't stay open forever
);

-- Every bid attempt, accepted or rejected. bid_id is generated by the client,
-- so a retry or double-click reuses it and the primary key rejects the duplicate.
CREATE TABLE bids (
  bid_id         VARCHAR(64) PRIMARY KEY,
  auction_id     BIGINT NOT NULL,
  bidder_id      BIGINT NOT NULL,
  amount         BIGINT NOT NULL,
  outcome        ENUM('ACCEPTED', 'REJECTED') NULL,
  reason         VARCHAR(32) NULL,
  end_time_after DATETIME(3) NULL,
  extended       BOOLEAN NULL,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_bids_auction (auction_id)
);
