import type { Pool, PoolConnection, ResultSetHeader, RowDataPacket } from 'mysql2/promise';

export type RejectReason = 'AUCTION_NOT_FOUND' | 'AUCTION_CLOSED' | 'AUCTION_ENDED' | 'BID_TOO_HIGH';

export type BidResult =
  | { accepted: true; amount: number; endTime: Date; extended: boolean }
  | { accepted: false; reason: RejectReason };

export interface BidInput {
  bidId: string;     // generated by the client; reused on retry
  auctionId: number;
  bidderId: number;
  amount: number;    // paise
}

/**
 * The whole acceptance rule in one statement. There is no read-then-write:
 * the conditions are evaluated against the row at the moment it is locked.
 * If two bids race, InnoDB makes the second wait for the first, then
 * re-checks the WHERE against the updated row, so only one can win.
 */
const ACCEPT_SQL = `
  UPDATE auctions
     SET best_bid = ?, best_bidder = ?
   WHERE id = ?
     AND status = 'OPEN'
     AND NOW(3) < end_time
     AND (   (best_bid IS NULL AND ? <= start_price)
          OR ? <= best_bid - decrement_step)`;

/**
 * Anti-sniping. Runs in the same transaction as the accept, while we still
 * hold the row lock, so the auction can't close between accepting the bid
 * and extending it.
 */
const EXTEND_SQL = `
  UPDATE auctions
     SET end_time = NOW(3) + INTERVAL extension_window_sec SECOND,
         extension_count = extension_count + 1
   WHERE id = ?
     AND end_time < NOW(3) + INTERVAL extension_window_sec SECOND
     AND extension_count < max_extensions`;

/**
 * Closing is a guarded write too, not a timer we trust. Whatever triggers it
 * (a scheduler, a sweeper) can fire late, early or twice: if the auction was
 * extended, this affects zero rows and the caller simply tries again later.
 */
const CLOSE_SQL = `
  UPDATE auctions
     SET status = 'CLOSED'
   WHERE id = ? AND status = 'OPEN' AND end_time <= NOW(3)`;

export async function placeBid(pool: Pool, bid: BidInput): Promise<BidResult> {
  const conn = await pool.getConnection();
  try {
    await conn.beginTransaction();

    // 1. Claim the bid id. A duplicate means this is a retry: return what
    //    happened the first time instead of bidding again.
    try {
      await conn.execute(
        'INSERT INTO bids (bid_id, auction_id, bidder_id, amount) VALUES (?, ?, ?, ?)',
        [bid.bidId, bid.auctionId, bid.bidderId, bid.amount],
      );
    } catch (err) {
      if (isDuplicateKey(err)) {
        await conn.rollback();
        return readStoredResult(conn, bid.bidId);
      }
      throw err;
    }

    // 2. The atomic accept.
    const [accept] = await conn.execute<ResultSetHeader>(ACCEPT_SQL, [
      bid.amount, bid.bidderId, bid.auctionId, bid.amount, bid.amount,
    ]);

    let result: BidResult;
    if (accept.affectedRows === 1) {
      const [extend] = await conn.execute<ResultSetHeader>(EXTEND_SQL, [bid.auctionId]);
      const [rows] = await conn.execute<RowDataPacket[]>(
        'SELECT end_time FROM auctions WHERE id = ?', [bid.auctionId],
      );
      result = {
        accepted: true,
        amount: bid.amount,
        endTime: rows[0].end_time,
        extended: extend.affectedRows === 1,
      };
    } else {
      result = { accepted: false, reason: await rejectionReason(conn, bid.auctionId) };
    }

    // 3. Record the outcome so a replay gets the same answer.
    await conn.execute(
      'UPDATE bids SET outcome = ?, reason = ?, end_time_after = ?, extended = ? WHERE bid_id = ?',
      result.accepted
        ? ['ACCEPTED', null, result.endTime, result.extended, bid.bidId]
        : ['REJECTED', result.reason, null, null, bid.bidId],
    );

    await conn.commit();
    return result;
  } catch (err) {
    await conn.rollback();
    throw err;
  } finally {
    conn.release();
  }
}

export async function closeAuction(pool: Pool, auctionId: number): Promise<boolean> {
  const [res] = await pool.execute<ResultSetHeader>(CLOSE_SQL, [auctionId]);
  return res.affectedRows === 1;
}

export interface NewAuction {
  startPrice: number;
  decrementStep: number;
  endsInMs: number;          // negative = already ended
  extensionWindowSec: number;
  maxExtensions: number;
}

export async function createAuction(pool: Pool, a: NewAuction): Promise<number> {
  const [res] = await pool.execute<ResultSetHeader>(
    `INSERT INTO auctions
       (start_price, decrement_step, end_time, extension_window_sec, max_extensions)
     VALUES (?, ?, NOW(3) + INTERVAL ? MICROSECOND, ?, ?)`,
    [a.startPrice, a.decrementStep, a.endsInMs * 1000, a.extensionWindowSec, a.maxExtensions],
  );
  return res.insertId;
}

// The decision has already been made atomically above. This read only
// explains a rejection to the caller, so it doesn't need to be locked.
async function rejectionReason(conn: PoolConnection, auctionId: number): Promise<RejectReason> {
  const [rows] = await conn.execute<RowDataPacket[]>(
    'SELECT status, end_time > NOW(3) AS running FROM auctions WHERE id = ?', [auctionId],
  );
  if (rows.length === 0) return 'AUCTION_NOT_FOUND';
  if (rows[0].status === 'CLOSED') return 'AUCTION_CLOSED';
  if (!rows[0].running) return 'AUCTION_ENDED';
  return 'BID_TOO_HIGH';
}

async function readStoredResult(conn: PoolConnection, bidId: string): Promise<BidResult> {
  const [rows] = await conn.execute<RowDataPacket[]>(
    'SELECT amount, outcome, reason, end_time_after, extended FROM bids WHERE bid_id = ?', [bidId],
  );
  const r = rows[0];
  return r.outcome === 'ACCEPTED'
    ? { accepted: true, amount: Number(r.amount), endTime: r.end_time_after, extended: Boolean(r.extended) }
    : { accepted: false, reason: r.reason };
}

function isDuplicateKey(err: unknown): boolean {
  return typeof err === 'object' && err !== null && (err as { errno?: number }).errno === 1062;
}
